version: '3'
services:
  ghost-build:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: emilol/ghost-cloudinary
  ghost:
    image: emilol/ghost-cloudinary
    restart: always
    volumes:
      - $INSTALL_PATH/content:${GHOST_INSTALL:-/var/lib/ghost}/content
      - $INSTALL_PATH/content.orig:${GHOST_INSTALL:-/var/lib/ghost}/content.orig
      - $CONFIG_PATH:${GHOST_INSTALL:-/var/lib/ghost}/config.production.json
    ports:
      - "2368:2368"
    environment:
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:?run export CLOUDINARY_CLOUD_NAME="your cloud name"}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:?run export CLOUDINARY_API_KEY="your api key"}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:?run export CLOUDINARY_API_SECRET="your api secret"}
    command: "bash -c \"su-exec node ghost config storage.cloudinary-store.cloud_name '$CLOUDINARY_CLOUD_NAME'; \
                        su-exec node ghost config storage.cloudinary-store.api_key '$CLOUDINARY_API_KEY'; \
                        su-exec node ghost config storage.cloudinary-store.api_secret '$CLOUDINARY_API_SECRET' &> /dev/null; \
                        node current/index.js\""